name: Update & Deploy Puzzle-A-Day Page

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install beautifulsoup4

      - name: Run puzzle-a-day.py
        run: python puzzle-a-day.py

      # Set up Node.js for React build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          cd docs/project
          npm ci

      - name: Build React app
        run: |
          cd docs/project
          npm run build

      - name: List build output
        run: ls -l docs/project/dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/project/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}